### ISSUE TITLE
There is a "debugger" symbol in the release file.

### ISSUE THREAD

**Issue by zrb0001** [KingMario/packages#1]
node_modules/ngx-lower-case-directive/esm2015/ngx-lower-case.directive.js

![image](https://user-images.githubusercontent.com/6268484/46710056-e9799000-cc78-11e8-9cb1-bfc51c220245.png)

**Comment by KingMario** [comment]
@zrb0001 Thanks for the bug reporting. I must have published the code under development by mistake.
A new version, v1.0.3 has just been published and it fixed the bug. Please update it by using npm update command.

Sorry for the inconvenience the bug caused.
