### ISSUE TITLE
nm, m istake

### ISSUE THREAD

**Issue by jarrodmedrano** [KingMario/packages#14]
<img width="428" alt="Screen Shot 2019-12-06 at 9 12 41 AM" src="https://user-images.githubusercontent.com/1929136/70337792-fd7f3a00-1808-11ea-878f-d63da78716f2.png">

**Comment by KingMario** [comment]
Hi @jarrodmedrano, it's a feature called `add period with double-space` of Mac OS and can be turned off from keyboard text preferences.

And I guess you‘ve already discovered that.
😀
