### ISSUE TITLE
Page gets stuck and browser gets hang if i enter spaces more than 5 time in angular 9.

### ISSUE THREAD

**Issue by mrigankgithub** [KingMario/packages#22]
I am using this directive in angular 9 with my project , but whenever i put multiple spaces in input field my browser and web page gets stuck. This directive supposed to trim my multiple space , it is working fine only when i put 3-4 spaces.

**Comment by KingMario** [comment]
Hi @mrigankgithub 

Could you please give me a reproduction link?

**Comment by KingMario** [comment]
Hi @mrigankgithub 

I haven't heard from you for a period. And it's not reproducible from my side. I'm closing this issue for now.

Feel free to reopen it when you think it's necessary.

Thanks.
