### ISSUE TITLE
Not setting trim value causes TrimOnWriteValue to not work

### ISSUE THREAD

**Issue by ThomasDevens** [KingMario/packages#24]
https://github.com/KingMario/packages/blob/559184662ec3cf5c7336617a3a18a8a4c1573c3e/projects/ngx-trim-directive/src/lib/ngx-trim.directive.ts#L20

I'm not sure if this was intended, but having an input s.t.
```<input ... trim [TrimOnWriteValue]="false"/>```

causes the TrimOnWriteValue=false case to not work because trim is undefined, so trim === false fails, causing the value to be trimmed.

Could fix this by setting trim to '' by default, but again, this might be intended behavior.

**Comment by KingMario** [comment]
Hi @ThomasDevens, thanks for the report.

TrimOnWriteValue is set false  to avoid the value being trimmed while the bound modal is changed programmatically, i.e., not by the user's keystroke on the `<input>` element. If it's set to false, while the value of bound modal is updated by API calls or other events, the value is not trimmed automatically.

Here is an example:

```html
<div>
  <input type="text" [(ngModel)]="name" trim [trimOnWriteValue]="false" size="80">
  <button (click)="name = 'Some string with trailing spaces    '">Change It</button>
</div>
<pre>"{{name}}"</pre>
```

When you click the button, the trailing spaces of the value is not trimmed.
You can remove the binding of `[trimOnWriteValue]="false"` to see the difference.

**Comment by ThomasDevens** [comment]
Better explanation of my issue: https://stackblitz.com/edit/ngx-trim-directive-issue-24?file=src%2Fapp%2Fapp.component.html

Again, this may be the intended behavior for not setting a value to "trim" (Not so much an issue with the TrimOnWriteValue option, as it has the same behavior with or without)

**Comment by KingMario** [comment]
Thanks for the explanation @ThomasDevens. I think it's illegal to bind the property like this: `[trim]=""` in Angular. To bind a property with '', you should write `[trim]="''"`.
Hence close this issue.
