### ISSUE TITLE
Ivy Compatibility

### ISSUE THREAD

**Issue by maks-humeniuk** [KingMario/packages#25]
I'm using `ngx-trim-directive` in Angular 13 project.

Overall it works fine, but `ng serve` shows this warning:
```
Processing legacy "View Engine" libraries:
- ngx-trim-directive [es2015/esm2015] (git+ssh://git@github.com/KingMario/packages.git)
Encourage the library authors to publish an Ivy distribution.
```

Do you have any plans to migrate to Ivy?

**Comment by KingMario** [comment]
Thanks for the report.

Let me try to fix it.

**Comment by KingMario** [comment]
Fixed by updating Angular to V13 in this temporary branch: https://github.com/KingMario/packages/tree/ivy-compatibility

Due to Angular's breaking changes of linting and testing, the fix is not pushed to the master branch.

Please install V2 and verify if it's Ivy compatible now.

Thanks.

**Comment by maks-humeniuk** [comment]
`ng serve` doesn't complain about `2.0.0`, thanks!

**Comment by ghost** [comment]
@KingMario When new version will be published? :)

**Comment by maks-humeniuk** [comment]
@ddontsov-b2broker, I just `npm i ngx-trim-directive@latest` and it installed `2.0.0`. So, I guess it's already published.

**Comment by KingMario** [comment]
@ddontsov-b2broker @Halfist Yes, I've already published the new version. You might have to specify `@2` or `@latest` to install it because of npm repository cache.

The source code will remain in the temporary branch till I have time to use `ng new` and `ng g` to create another workspace and generate libraries (incuding ngx-cleave-directive, etc.) with proper linting and testing settings.

Thanks for you confirmation.

Hence close this issue. Thanks.

**Comment by coyoteecd** [comment]
@KingMario can you please merge to master and add 2.0.0 to the releases tab or at least tag the release commit you published from?

**Comment by KingMario** [comment]
@coyoteecd Thanks for the suggestion. 2.0.0 tag is added to the release commit.

One problem is that the tag is for ngx-trim-directive only while there are several libraries in this repo. I'm thinking about split this repo into several repos so that each library can have its own repo.

**Comment by exequiel09** [comment]
@KingMario I don't think `ngx-cleave-directive@2.0.0` is published. Can we publish it? Thanks
