### ISSUE TITLE
 Ivy distribution

### ISSUE THREAD

**Issue by hkjeffchan** [KingMario/packages#27]
With angular 14 build, it will show the following:

- ngx-upper-case-directive [es2015/esm2015] (git+ssh://git@github.com/KingMario/packages.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by KingMario** [comment]
Hi @hkjeffchan I've just published version 2 of ngx-upper-case-directive.

Could you please check if the warning has gone.

Thanks

**Comment by hkjeffchan** [comment]
Yes, the warning is gone. Thanks!
