### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by lujakob** [KingMario/packages#29]
With the latest version 16 of Angular View Engine libs are not supported anymore. ngcc is removed.

https://medium.com/@katsuba.igor/the-removal-of-angular-compatibility-compiler-ngcc-in-angular-16-83e685552ab3

It would be great to have this extension running in Angular 16

**Comment by KingMario** [comment]
Hi @lujakob, thanks for the information.

Because of unit test and lint issues for direct upgrade, I'll create a new project in a new repo for the new version. Will let you know when it's done.

**Comment by lujakob** [comment]
> Hi @lujakob, thanks for the information.
> 
> Because of unit test and lint issues for direct upgrade, I'll create a new project in a new repo for the new version. Will let you know when it's done.

Awesome, thx.

**Comment by KingMario** [comment]
Hi @lujakob 

If I understand correctly, the library you are talking about is [ngx-trim-directive](https://www.npmjs.com/package/ngx-trim-directive), right?

ngx-trim-directive V3.0.0 published.

Other libraries such as[ ngx-cleave-directive](https://www.npmjs.com/package/ngx-cleave-directive) in this repository are being detached into separate repositories.

**Comment by lujakob** [comment]
> Hi @lujakob
> 
> If I understand correctly, the library you are talking about is [ngx-trim-directive](https://www.npmjs.com/package/ngx-trim-directive), right?
> 
> ngx-trim-directive V3.0.0 published.
> 
> Other libraries such as[ ngx-cleave-directive](https://www.npmjs.com/package/ngx-cleave-directive) in this repository are being detached into separate repositories.

Exactly, awesome thanks!

**Comment by KingMario** [comment]
> Exactly, awesome thanks!

@lujakob you are welcome.
