### ISSUE TITLE
Angular 8 compatibiliy: ngx-trim-directive errors on page load

### ISSUE THREAD

**Issue by lujakob** [KingMario/packages#5]
I am using ngx-trim-directive trim directive with Angular Material FormField. Since my upgrade to version 8, the form errors on page load instantly. I reproduced to bug in a stackblitz:

https://stackblitz.com/edit/angular-rqhhec

Both email and password field are required fields. Email uses the trim directive and it is errored on page load. Password field does not use it and is fine.

**Comment by KingMario** [comment]
Hi @lujakob,

Thanks for the report.

Please use back the version 1.0.3, which is compatible with Angular 8 as well.

I'll fix the bug later.

**Comment by KingMario** [comment]
https://stackblitz.com/edit/angular-9f9y6a
