### ISSUE TITLE
Angular 8 compatibiliy: ngx-trim directive fails on undefined input value 

### ISSUE THREAD

**Issue by n1c086** [KingMario/packages#7]
I used the library (last version) with angular 6 and I found no issue.
After upgrading to angular 8 the following error appears.

This is my html file:
**<input type="text" [(ngModel)]="host" class="form-control" placeholder="e.g 192.168.1.1" aria-label="Host" aria-describedby="basic-addon1" trim>**

I defined in the related file.ts the following property:
**private host: string;**

This is the error when  page is loaded:
**TypeError: Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at DefaultValueAccessor._valueAccessor.writeValue (ngx-trim-directive.js:105)**

The error disappear if i set this:
**private host: string= "";**

Hope is simple to solve.
Many thanks

**Comment by KingMario** [comment]
@n1c086Thank you for reporting this issue.

It was resolved in the just released version 1.0.8.

BTW, you might also be interested in another input manipulating directive by me, ngx-cleave-directive.

Demo of both directives: https://stackblitz.com/edit/angular-7o3mug

&

[cleave.js office site](https://nosir.github.io/cleave.js/)

Thanks.
